### PR TITLE
Change IndexError to a meaningful error message

### PR DESCRIPTION
**Pull request by vcidst**
When there are no deployements, telepresence crashes with an uncaught IndexError. It should exit with a meaningful error message instead. 

Error message: No Deployements Found

### CODE REVIEW

**Comment by avinassh** [comment]
Umm, it catches any error that could happen and report as no deployment found. We need to make sure  that thats the error. 

One good way to ensure is, checking if `items` array is zero?

**Comment by vcidst** [comment]
Yes, that would be better. I've changed the try-catch block into a condition in 
e934a0c539cc7032e7d8b8c8f354efcff03106cc

**Comment by vcidst** [comment]
I think this brakes something, unable to run this telepresence executable after this change. Closing the PR

```
$ usr/local/bin/telepresence --mount=false --also-proxy=10.0.0.0/8 --run bash
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence 
T: can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. 
T: For a full list of method limitations see https://telepresence.io/reference/methods.html

Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "usr/local/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 90, in start_proxy
    run_id=run_id,
  File "usr/local/bin/telepresence/telepresence/proxy/remote.py", line 155, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "usr/local/bin/telepresence/telepresence/proxy/remote.py", line 96, in get_deployment_json
    stderr=STDOUT
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


And here are the last few lines of the logfile (see /home/zi/Work/2020/Verloop/Github/telepresence_verloop/telepresence.log for the complete logs):

   0.7 TEL | [4] Capturing: kubectl config view -o json
   0.8 TEL | [5] Capturing: kubectl get ns default
   1.3 TEL | Command: kubectl 1.15.9
   1.3 TEL | Context: stage, namespace: default, version: 1.15.9-gke.24
   1.3 TEL | END SPAN startup.py:58(__init__)    1.3s
   1.3 TEL | [6] Capturing: ssh -V
   1.3 TEL | [7] Running: sudo -n echo -n
   1.3 >>> | Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
   1.3 TEL | [8] Capturing: kubectl --context stage --namespace default get pods telepresence-connectivity-check --ignore-not-found
   3.1 TEL | Scout info: {'latest_version': '0.104', 'application': 'telepresence', 'notices': []}
   3.1 TEL | BEGIN SPAN deployment.py:44(create_new_deployment)
   3.1 TEL | [9] Capturing: kubectl --context stage --namespace default delete --ignore-not-found svc,deploy --selector=telepresence=a535906daf6a47528a28590cb2fad9c3
   4.1 TEL | [9] captured in 1.02 secs.
   4.1 TEL | [10] Capturing: kubectl --context stage --namespace default run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1586189822-7674477-31297 --image=datawire/telepresence-k8s:0.103 --labels=telepresence=a535906daf6a47528a28590cb2fad9c3
   4.5  10 | kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
   4.7 TEL | END SPAN deployment.py:44(create_new_deployment)    1.6s
   4.7 TEL | BEGIN SPAN remote.py:153(get_remote_info)
   4.7 TEL | BEGIN SPAN remote.py:73(get_deployment_json)
   4.7 TEL | [11] Capturing: kubectl --context stage --namespace default get deployment -o json --export --selector=telepresence=a535906daf6a47528a28590cb2fad9c3
   5.1 TEL | END SPAN remote.py:73(get_deployment_json)    0.4s

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]: n
T: Exit cleanup in progress

```

**Comment by avinassh** [comment]
The changes look correct, not sure why it broke it. Also, it should be `len(deployements)` right? 🤔

**Pull request closed without merging**
